export const appRoutes = {
    Empty: '',
    App: 'app',
    Login: 'login',
    SignUp: 'signUp',
    Dashboard: 'dashboard',
    Together: 'together',
    TogetherAsk: 'together-ask',
    TogetherChat: 'together-chat',
    TogetherChatId: 'chatId',
    TogetherConnect: 'together-connect',
    TogetherSwipe: 'together-swipe',
    Group: 'group',
    Create: 'create',
    Learn: 'learn',
    Challenge: 'challenge',
    Test: 'test',
    Draw: 'draw',
    Settings: 'settings'
}
