export const endpoints = {
    FileUploadDownload: 'fileUploadDownload',
    FileUploadDownloadAnonymous: 'fileUploadDownloadAnonymous',
    GroupFiles: 'groupFiles', // use get / post
    GroupInfo: 'groupInfo',
    GroupLeave: 'groupLeave',
    GroupMessages: 'groupMessages',
    GroupOverview: 'groupOverview',
    GroupPossibleUsers: 'groupPossibleUsers',
    TogetherAskUser: 'togetherAskUser',
    TogetherChat: 'togetherChat',
    TogetherConnectUser: 'togetherConnectUser',
    TogetherSwipeUser: 'togetherSwipeUser',
    TogetherUsersFilter: 'togetherUsersFilter',
    UserDarkTheme: 'userDarkTheme',
    UserLanguage: 'userLanguage',
    UserLogin: 'userLogin',
    UserProfile: 'userProfile',
    UserRefreshToken: 'userRefreshToken',
    UserSignUp: 'userSignUp',
    WebSocket: 'learnzsocket',
    WebSocketConnections: 'webSocketConnections',
}