export const endpoints = {
    ChallengeActive: 'challengeActive',
    ChallengeAnswer: 'challengeAnswer',
    ChallengeFlow: 'challengeFlow',
    ChallengeOpen: 'challengeOpen',
    CreateFilterSets: 'createFilterSets',
    CreateLastSets: 'createLastSets',
    CreateOwnSets: 'createOwnSets',
    CreateSetHeader: 'createSetHeader',
    CreateSetQuestions: 'createSetQuestions',
    DrawCollections: 'drawCollections', // todo get - draw, post - setting, delete - delete confirm
    DrawPages: 'drawPages', // todo get - drawing, post - drawing, put - drawing, delete - delete confirm
    DrawSegments: 'drawSegments', // todo get / post
    FileChangePolicy: 'fileChangePolicy',
    FileUploadDownload: 'fileUploadDownload',
    FileUploadDownloadAnonymous: 'fileUploadDownloadAnonymous',
    FileVersions: 'fileVersions',
    FileVersionUploadDownload: 'fileVersionUploadDownload',
    GroupFiles: 'groupFiles',
    GroupInfo: 'groupInfo',
    GroupLeave: 'groupLeave',
    GroupMessages: 'groupMessages',
    GroupOverview: 'groupOverview',
    GroupPossibleUsers: 'groupPossibleUsers',
    LearnClosedSession: 'learnClosedSession',
    LearnMarkQuestion: 'learnMarkQuestion',
    LearnOpenSession: 'learnOpenSession',
    LearnQuestionAnswerCard: 'learnQuestionAnswerCard',
    LearnQuestionAnswerWrite: 'learnQuestionAnswerWrite',
    LearnQuestionSetCorrect: 'learnQuestionSetCorrect',
    LearnSessionQuestions: 'learnSessionQuestions',
    TestClosed: 'testClosed',
    TestCreate: 'testCreate',
    TestEnd: 'testEnd',
    TestGroupAdjustUserPoints: 'testGroupAdjustUserPoints',
    TestGroupTestCreate: 'testGroupTestCreate',
    TestOpen: 'testOpen',
    TestPossibleGroups: 'testPossibleGroups',
    TestQuestions: 'testQuestions',
    TestResult: 'testResult',
    TestResultOverview: 'testResultOverview',
    TestSettings: 'testSettings',
    TestStart: 'testStart',
    TestVisibility: 'testVisibility',
    TogetherAskUser: 'togetherAskUser',
    TogetherChat: 'togetherChat',
    TogetherConnectUser: 'togetherConnectUser',
    TogetherSwipeUser: 'togetherSwipeUser',
    TogetherUsersFilter: 'togetherUsersFilter',
    UserDarkTheme: 'userDarkTheme',
    UserLanguage: 'userLanguage',
    UserLogin: 'userLogin',
    UserProfile: 'userProfile',
    UserRefreshToken: 'userRefreshToken',
    UserSignUp: 'userSignUp',
    WebSocket: 'learnzsocket',
    WebSocketConnections: 'webSocketConnections',
}